\hypertarget{class_x_out_of_bounds}{}\section{X\+Out\+Of\+Bounds Klassenreferenz}
\label{class_x_out_of_bounds}\index{X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}}


Ausnahmeklasse Abgeleitete Klasse von std\+::exception. Speichert Ausnahmen und gibt diese auch wieder aus.  




{\ttfamily \#include $<$X\+Out\+Of\+Bounds.\+hpp$>$}



Klassendiagramm für X\+Out\+Of\+Bounds\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=181pt]{class_x_out_of_bounds__inherit__graph}
\end{center}
\end{figure}


Zusammengehörigkeiten von X\+Out\+Of\+Bounds\+:
\nopagebreak
\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[width=181pt]{class_x_out_of_bounds__coll__graph}
\end{center}
\end{figure}
\subsection*{Öffentliche Methoden}
\begin{DoxyCompactItemize}
\item 
\hyperlink{class_x_out_of_bounds_a9e2fc4dfa3f25d730563ff2492f40662}{X\+Out\+Of\+Bounds} (const char $\ast$msg)
\item 
virtual \hyperlink{class_x_out_of_bounds_a7655380482ddb2f03570caee39fa2748}{$\sim$\+X\+Out\+Of\+Bounds} ()  throw ()
\item 
const char $\ast$ \hyperlink{class_x_out_of_bounds_a5a047c4fa3db7ef57de7732ae4a2e937}{what} () const  throw ()
\begin{DoxyCompactList}\small\item\em Getter Kann aufgrund von throw() selbst keine exceptions werfen. \end{DoxyCompactList}\end{DoxyCompactItemize}


\subsection{Ausführliche Beschreibung}
Ausnahmeklasse Abgeleitete Klasse von std\+::exception. Speichert Ausnahmen und gibt diese auch wieder aus. 

\subsection{Beschreibung der Konstruktoren und Destruktoren}
\mbox{\Hypertarget{class_x_out_of_bounds_a9e2fc4dfa3f25d730563ff2492f40662}\label{class_x_out_of_bounds_a9e2fc4dfa3f25d730563ff2492f40662}} 
\index{X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}!X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}}
\index{X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}!X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}}
\subsubsection{\texorpdfstring{X\+Out\+Of\+Bounds()}{XOutOfBounds()}}
{\footnotesize\ttfamily X\+Out\+Of\+Bounds\+::\+X\+Out\+Of\+Bounds (\begin{DoxyParamCaption}\item[{const char $\ast$}]{msg }\end{DoxyParamCaption})}

Konstruktor 
\begin{DoxyParams}{Parameter}
{\em msg} & Beschreibung / Bezeichnung der Ausnahme \\
\hline
\end{DoxyParams}
\mbox{\Hypertarget{class_x_out_of_bounds_a7655380482ddb2f03570caee39fa2748}\label{class_x_out_of_bounds_a7655380482ddb2f03570caee39fa2748}} 
\index{X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}!````~X\+Out\+Of\+Bounds@{$\sim$\+X\+Out\+Of\+Bounds}}
\index{````~X\+Out\+Of\+Bounds@{$\sim$\+X\+Out\+Of\+Bounds}!X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}}
\subsubsection{\texorpdfstring{$\sim$\+X\+Out\+Of\+Bounds()}{~XOutOfBounds()}}
{\footnotesize\ttfamily X\+Out\+Of\+Bounds\+::$\sim$\+X\+Out\+Of\+Bounds (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) throw  ) \hspace{0.3cm}{\ttfamily [virtual]}}

Destruktor

Kann aufgrund von throw() selbst keine exceptions werfen. 

\subsection{Dokumentation der Elementfunktionen}
\mbox{\Hypertarget{class_x_out_of_bounds_a5a047c4fa3db7ef57de7732ae4a2e937}\label{class_x_out_of_bounds_a5a047c4fa3db7ef57de7732ae4a2e937}} 
\index{X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}!what@{what}}
\index{what@{what}!X\+Out\+Of\+Bounds@{X\+Out\+Of\+Bounds}}
\subsubsection{\texorpdfstring{what()}{what()}}
{\footnotesize\ttfamily const char $\ast$ X\+Out\+Of\+Bounds\+::what (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption}) const throw  ) }



Getter Kann aufgrund von throw() selbst keine exceptions werfen. 

\begin{DoxyReturn}{Rückgabe}
Beschreibung / Bezeichnung der Ausnahme 
\end{DoxyReturn}


Die Dokumentation für diese Klasse wurde erzeugt aufgrund der Dateien\+:\begin{DoxyCompactItemize}
\item 
C\+:/portable\+Dev\+Env\+\_\+2017/workspace2017/project/src/\hyperlink{_x_out_of_bounds_8hpp}{X\+Out\+Of\+Bounds.\+hpp}\item 
C\+:/portable\+Dev\+Env\+\_\+2017/workspace2017/project/src/\hyperlink{_x_out_of_bounds_8cpp}{X\+Out\+Of\+Bounds.\+cpp}\end{DoxyCompactItemize}
